### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by vaaski** [mrcoles/bookmarklet#11]
Hi, when I try to use this it says that the regeneratorRuntime is not defined.
A quick google shows that it's missing the Babel polyfill.

[adding it via](https://i.imgur.com/r1MqhNz.png) `@script` [does not work](https://i.imgur.com/I5UHZaA.png).
only loading it prior to executing the bookmarklet works.

maybe make Babel toggleable with a command line flag?

**Comment by mrcoles** [comment]
Hey @vaaski are you using an `await` in your code? Do you have a code sample?

**Comment by vaaski** [comment]
I honestly forgot where I wanted to use this haha, I guess it's been a couple of months.
If you want I can try to reproduce it again, let me know.
