### ISSUE TITLE
js-core dependency complains that it needs to be upgraded to js-core 3

### ISSUE THREAD

**Issue by roa-nyx** [mrcoles/bookmarklet#13]
When installing the bookmarklet module NPM warns us that the js-core < 3 has a number of issues and should not be used.

EDIT: Confirmed that this is an issue of `babel-core` and `babel-preset-env`. There seems to be an outstanding PR to upgrade to a newer version of babel. Possible fix for this?

**Comment by mrcoles** [comment]
@roa-nyx I dropped babel support for now, LMK if you’d like to see it incorporated again. There were issues with regenerator-runtime dependencies and whatnot, so it seemed easiest to remove it. Folks who want other transforms can always run them before they run this script.
