### ISSUE TITLE
Class Fields not supported by babel in bookemarklet

### ISSUE THREAD

**Issue by rwadkins** [mrcoles/bookmarklet#17]
I wrote a bookmarklet using ES6 Classes and used class fields in my code. babylon is throwing an error, because, it seems that class fields aren't supported in babel preset env.  
[bablylonError.txt](https://github.com/mrcoles/bookmarklet/files/5142597/bablylonError.txt)

**Comment by mrcoles** [comment]
@rwadkins I removed Babel with [v3.0.0](https://github.com/mrcoles/bookmarklet/releases/tag/v3.0.0). LMK if dropping it entirely and relying the browser’s native support works for you!
