### ISSUE TITLE
-d option no longer documented in help (plus a typo)

### ISSUE THREAD

**Issue by matatk** [mrcoles/bookmarklet#18]
The README in this repo shows that there's a `-d` option to make a demo page, which is neat. However, when running `bookmarklet -h` in the terminal, this isn't document. Also there's a spurious `'` in the output, after "stdout".

Just found this tool and it looks really helpful, thanks :-).

**Comment by mrcoles** [comment]
fixed https://github.com/mrcoles/bookmarklet/commit/47dfa5b7dd79b5082c0f8bd8608112cbba4aa742
