### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined SOLVED

### ISSUE THREAD

**Issue by wspresto** [mrcoles/bookmarklet#20]
I am posting for the next unfortunate one who is hoping to find a solution for the regeneratorRuntime issue.
I could be persuaded to submit a PR, but it appears the author has abandoned this project so there is no incentive there.

Here is what I did.

1. cloned the project
2. removed all babel dependencies from package.json and code.
3. replaced "uglify-js" with "terser"
4. Here is the function that you have to change.
`function minify(code) {
  return terser.minify(code).code;
}`

ta-dah. No more questionably useful babel transpilations.

**Comment by mrcoles** [comment]
Give this a try: https://github.com/mrcoles/bookmarklet/releases/tag/v3.0.0
